
//creates empty array to hold description of each keycode
var keyCodeLookup = [];

//add known codes in numeric order plz
keyCodeLookup[8] = "Backspace";
keyCodeLookup[9] = "Tab";
keyCodeLookup[17] = "Ctrl";
keyCodeLookup[18] = "Alt";
keyCodeLookup[20] = "Caps";
keyCodeLookup[48] = "0";
keyCodeLookup[49] = "1";
keyCodeLookup[50] = "2";
keyCodeLookup[51] = "3";
keyCodeLookup[52] = "4";
keyCodeLookup[53] = "5";
keyCodeLookup[49] = "6";
keyCodeLookup[49] = "7";
keyCodeLookup[49] = "8";
keyCodeLookup[49] = "9";
keyCodeLookup[61] = "+=";
keyCodeLookup[69] = "A";
keyCodeLookup[66] = "B";
keyCodeLookup[67] = "C";
keyCodeLookup[68] = "D";
keyCodeLookup[69] = "E";
keyCodeLookup[70] = "F";
keyCodeLookup[71] = "G";
keyCodeLookup[72] = "H";
keyCodeLookup[73] = "I";
keyCodeLookup[74] = "J";
keyCodeLookup[75] = "K";
keyCodeLookup[76] = "L";
keyCodeLookup[77] = "M";
keyCodeLookup[78] = "N";
keyCodeLookup[79] = "O";
keyCodeLookup[80] = "P";
keyCodeLookup[81] = "Q";
keyCodeLookup[82] = "R";
keyCodeLookup[83] = "S";
keyCodeLookup[84] = "T";
keyCodeLookup[85] = "U";
keyCodeLookup[86] = "V";
keyCodeLookup[87] = "W";
keyCodeLookup[88] = "X";
keyCodeLookup[89] = "Y";
keyCodeLookup[90] = "Z";
keyCodeLookup[91] = "Pengu";
keyCodeLookup[109] = "NUM -";
keyCodeLookup[173] = "-_";
keyCodeLookup[192] = "~`";
keyCodeLookup[220] = "\\ \|";
keyCodeLookup[221] = "\] \}";
